import{describe,expect,it,vi}from"vitest";import{ContactChatResolver}from"../src/amocrm/contact-resolver.js";
describe("official contact/chat linking",()=>{it("matches exact normalized phone, creates a chat without an unsupported External Integration source, and enriches the contact",async()=>{const rest={searchContacts:vi.fn(async()=>({_embedded:{contacts:[{id:10,custom_fields_values:[{field_code:"PHONE",values:[{value:"+7 (999) 123-45-67"}]}],_embedded:{leads:[{id:20}]}}]}})),linkChatToContact:vi.fn(async()=>({})),patchContact:vi.fn(async()=>({}))};const chats={createChat:vi.fn(async()=>({id:"amo-chat-uuid"}))};const resolver=new ContactChatResolver(rest as any,chats as any,{telegramUsernameFieldId:100,telegramIdFieldId:101});const contact=await resolver.findExactByPhone("79991234567");const result=await resolver.createChatAndLink({id:"a",messenger:"telegram",providerAccountId:"p",credentialRef:"s",amoAccountId:"amo",amoScopeId:"scope",sourceExternalId:"source",config:{},state:"connected"},"provider-chat",{externalId:"user",displayName:"Client",username:"client",phone:"79991234567",profile:{telegramId:"user",firstName:"Client"}},contact!);expect(result).toMatchObject({amoConversationId:"amo-chat-uuid",contactId:10});expect(rest.linkChatToContact).toHaveBeenCalledWith(10,"amo-chat-uuid");expect(rest.patchContact).toHaveBeenCalledWith(10,expect.objectContaining({name:"Client",first_name:"Client",custom_fields_values:expect.arrayContaining([expect.objectContaining({field_id:100}),expect.objectContaining({field_id:101})])}));const payload=(chats.createChat.mock.calls as unknown as Array<[string,Record<string,unknown>]>)[0]![1];expect(payload).toMatchObject({user:{profile_link:"https://t.me/client"}});expect(payload.source).toBeUndefined();});});

describe("contact creation and enrichment",()=>{
 const participant={externalId:"7093946401",phone:"2349128858876",username:"ericafahelu",profile:{telegramId:"7093946401",firstName:"Тест",lastName:"Интеграции",username:"ericafahelu",phone:"2349128858876",isBot:false}};
 it("creates a contact before the chat when no exact phone match exists",async()=>{const rest={searchContacts:vi.fn(async()=>({_embedded:{contacts:[]}})),createContact:vi.fn(async()=>({_embedded:{contacts:[{id:11,custom_fields_values:[]}]}})),linkChatToContact:vi.fn(async()=>({})),patchContact:vi.fn(async()=>({}))};const chats={createChat:vi.fn(async()=>({id:"chat-11"}))};const resolver=new ContactChatResolver(rest as any,chats as any,{telegramUsernameFieldId:100,telegramIdFieldId:101});const contact=await resolver.ensureContact(participant);await resolver.createChatAndLink({id:"a",messenger:"telegram",providerAccountId:"p",credentialRef:"s",amoAccountId:"amo",amoScopeId:"scope",sourceExternalId:"source",config:{},state:"connected"},"tg-11",participant,contact);expect(contact.contactId).toBe(11);expect(rest.createContact).toHaveBeenCalledWith(expect.objectContaining({name:"Тест Интеграции",first_name:"Тест",last_name:"Интеграции",custom_fields_values:expect.arrayContaining([expect.objectContaining({field_code:"PHONE"}),expect.objectContaining({field_id:100}),expect.objectContaining({field_id:101})])}));expect(rest.linkChatToContact).toHaveBeenCalledWith(11,"chat-11");});
 it("creates a contact without a phone and does not invent custom fields when IDs are unset",async()=>{const rest={createContact:vi.fn(async()=>({_embedded:{contacts:[{id:12}]}})),searchContacts:vi.fn(),patchContact:vi.fn()};const resolver=new ContactChatResolver(rest as any,{} as any);const contact=await resolver.ensureContact({externalId:"99",username:"fallback",profile:{telegramId:"99"}});expect(contact.contactId).toBe(12);expect(rest.searchContacts).not.toHaveBeenCalled();expect(rest.createContact).toHaveBeenCalledWith({name:"fallback"});});
 it("refreshes an existing contact profile instead of creating a duplicate",async()=>{const existing={id:13,custom_fields_values:[{field_code:"PHONE",values:[{value:"2349128858876"}]}]};const rest={searchContacts:vi.fn(async()=>({_embedded:{contacts:[existing]}})),createContact:vi.fn(),patchContact:vi.fn(async()=>({}))};const resolver=new ContactChatResolver(rest as any,{} as any,{telegramUsernameFieldId:100,telegramIdFieldId:101});const contact=await resolver.ensureContact(participant);expect(contact.contactId).toBe(13);expect(rest.createContact).not.toHaveBeenCalled();expect(rest.patchContact).toHaveBeenCalledWith(13,expect.objectContaining({name:"Тест Интеграции",custom_fields_values:expect.arrayContaining([expect.objectContaining({field_id:100,values:[{value:"ericafahelu"}]}),expect.objectContaining({field_id:101,values:[{value:"7093946401"}]})])}));});
});
