import { describe, expect, it, vi } from "vitest";
import { exchangeAmoAuthorizationCode, RefreshingAmoTokenProvider } from "../src/amocrm/oauth-token-provider.js";
import { InMemorySecretStore } from "../src/security/secret-store.js";

describe("amoCRM OAuth token provider",()=>{
 it("rotates and persists access/refresh tokens in test mode",async()=>{const secrets=new InMemorySecretStore();await secrets.put("amo",{accessToken:"old",refreshToken:"refresh-old",expiresAt:0});const transport=vi.fn(async()=>new Response(JSON.stringify({access_token:"new",refresh_token:"refresh-new",expires_in:86400})));const provider=new RefreshingAmoTokenProvider({baseUrl:"https://test.amocrm.ru",integrationId:"id",clientSecret:"secret",redirectUri:"https://bridge/callback",credentialRef:"amo",secrets,writesAllowed:true,transport,now:()=>1000});expect(await provider.getAccessToken()).toBe("new");expect(await secrets.get("amo")).toMatchObject({accessToken:"new",refreshToken:"refresh-new"});});
 it("never refreshes through a read-only production provider",async()=>{const secrets=new InMemorySecretStore();await secrets.put("amo",{accessToken:"old",refreshToken:"refresh",expiresAt:0});const transport=vi.fn();const provider=new RefreshingAmoTokenProvider({baseUrl:"https://prod.amocrm.ru",integrationId:"id",clientSecret:"secret",redirectUri:"https://bridge/callback",credentialRef:"amo",secrets,writesAllowed:false,transport});await expect(provider.getAccessToken()).rejects.toThrow("read-only");expect(transport).not.toHaveBeenCalled();});
 it("exchanges an authorization code and persists the tokens",async()=>{const secrets=new InMemorySecretStore();let request:RequestInit|undefined;const transport=vi.fn(async(_url:RequestInfo|URL,init?:RequestInit)=>{request=init;return new Response(JSON.stringify({access_token:"access",refresh_token:"refresh",expires_in:3600}));});await exchangeAmoAuthorizationCode({baseUrl:"https://test.amocrm.ru",integrationId:"id",clientSecret:"secret",redirectUri:"https://sinaichannel.ru/oauth/callback",credentialRef:"amocrm:primary",secrets,writesAllowed:true,transport,now:()=>1000},"code");expect(transport).toHaveBeenCalledWith("https://test.amocrm.ru/oauth2/access_token",expect.objectContaining({method:"POST"}));expect(JSON.parse(request!.body as string)).toEqual({client_id:"id",client_secret:"secret",grant_type:"authorization_code",code:"code",redirect_uri:"https://sinaichannel.ru/oauth/callback"});expect(await secrets.get("amocrm:primary")).toEqual({accessToken:"access",refreshToken:"refresh",expiresAt:3601000});});
 it("exchanges an authorization code in read-only mode without enabling CRM writes",async()=>{const secrets=new InMemorySecretStore();const transport=vi.fn(async()=>new Response(JSON.stringify({access_token:"access",refresh_token:"refresh",expires_in:3600})));await exchangeAmoAuthorizationCode({baseUrl:"https://prod.amocrm.ru",integrationId:"id",clientSecret:"secret",redirectUri:"https://bridge/callback",credentialRef:"amo",secrets,writesAllowed:false,transport},"code");expect(transport).toHaveBeenCalledOnce();expect(await secrets.get("amo")).toMatchObject({accessToken:"access",refreshToken:"refresh"});});
});
