import{describe,expect,it,vi}from"vitest";
import{MessageRouter}from"../src/router/message-router.js";
import{InMemoryMappingStore}from"../src/storage/mapping-store.js";
import{InMemoryAccountRepository}from"../src/storage/account-repository.js";
import{InMemoryAdapterRegistry,type MessengerAdapter}from"../src/adapters/messenger-adapter.js";
import type{MessengerKind,NormalizedMessage,SendMessageCommand}from"../src/domain/messages.js";

function adapter(kind:MessengerKind,id:string,recipient="provider-user-42"):{value:MessengerAdapter;send:ReturnType<typeof vi.fn>;resolve:ReturnType<typeof vi.fn>}{const send=vi.fn(async(_c:SendMessageCommand)=>({externalMessageId:"provider-message",status:"sent" as const,occurredAt:new Date("2026-01-01T00:00:00Z")}));const resolve=vi.fn(async()=>({providerRecipientId:recipient,providerConversationId:`conversation-${recipient}`}));return{send,resolve,value:{kind,accountId:id,connect:async()=>{},disconnect:async()=>{},send,onInbound:()=>{},onStatus:()=>{},health:async()=>({connected:true}),resolveRecipient:resolve}};}
async function setup(kind:MessengerKind="telegram"){const accounts=new InMemoryAccountRepository();await accounts.upsert({id:"account-1",messenger:kind,providerAccountId:"provider-account",credentialRef:"secret",amoAccountId:"amo-1",amoScopeId:"scope-1",sourceExternalId:"source-1",config:{},state:"connected"});const store=new InMemoryMappingStore();const registry=new InMemoryAdapterRegistry();const a=adapter(kind,"account-1");registry.register(a.value);const chats={sendMessage:vi.fn(async()=>({new_message:{msgid:"amo-message"}})),updateDeliveryStatus:vi.fn()} as any;return{accounts,store,registry,a,chats,router:new MessageRouter({accounts,store,adapters:registry,chats,now:()=>new Date("2026-01-01T00:00:00Z")})};}
const inbound:NormalizedMessage={id:"in-1",messenger:"telegram",accountId:"account-1",conversationId:"provider-chat",direction:"inbound",sender:{externalId:"provider-user",phone:"+79990000000"},text:"hello",attachments:[],occurredAt:new Date("2026-01-01T00:00:00Z"),status:"delivered"};

describe("full router flow",()=>{
 it("routes inbound without an unsupported External Integration source and preserves the safe Telegram peer/profile",async()=>{const s=await setup();const message={...inbound,sender:{externalId:"provider-user",displayName:"Ada Lovelace",username:"ada",profile:{firstName:"Ada",lastName:"Lovelace",username:"ada",isBot:false},recipientReference:{kind:"telegram_input_peer_user" as const,userId:"provider-user",accessHash:"safe-access-hash"}}};await s.router.routeInbound(message);expect(s.chats.sendMessage).toHaveBeenCalledOnce();const payload=(s.chats.sendMessage.mock.calls as unknown as Array<[string,any]>)[0]![1];expect(payload.payload.source).toBeUndefined();expect(payload.payload.sender).toMatchObject({id:"provider-user",name:"Ada Lovelace"});const mapping=await s.store.getConversation("telegram","account-1","provider-chat");expect(mapping).toMatchObject({providerRecipientId:"provider-user",providerRecipientRef:{userId:"provider-user",accessHash:"safe-access-hash"},providerProfile:{firstName:"Ada",lastName:"Lovelace",username:"ada",isBot:false}});});
 it("updates the stored safe Telegram profile on later inbound messages",async()=>{const s=await setup();await s.router.routeInbound({...inbound,sender:{externalId:"provider-user",displayName:"old",profile:{firstName:"Old"}}});await s.router.routeInbound({...inbound,id:"in-2",sender:{externalId:"provider-user",displayName:"New Name",profile:{firstName:"New",lastName:"Name",username:"new"},recipientReference:{kind:"telegram_input_peer_user",userId:"provider-user",accessHash:"new-hash"}}});expect(await s.store.getConversation("telegram","account-1","provider-chat")).toMatchObject({providerProfile:{firstName:"New",lastName:"Name",username:"new"},providerRecipientRef:{accessHash:"new-hash"}});});
 it("outbound always uses saved provider IDs, never amoCRM receiver.id, and a recovered job cannot resend",async()=>{const s=await setup();await s.store.upsertConversation({messenger:"telegram",messengerAccountId:"account-1",providerConversationId:"tg-chat-real",providerRecipientId:"tg-user-real",amoConversationId:"amo-conv",amoScopeId:"scope-1"});const hook={message:{conversation:{id:"amo-conv"},receiver:{id:"amo-participant-wrong"},message:{id:"amo-out",type:"text",text:"reply"}}};await s.router.routeAmoOutbound(hook,"scope-1");await s.router.routeAmoOutbound(hook,"scope-1");const command=s.a.send.mock.calls[0]![0] as SendMessageCommand;expect(command).toMatchObject({conversationId:"tg-chat-real",recipientId:"tg-user-real"});expect(JSON.stringify(command)).not.toContain("amo-participant-wrong");expect(s.a.send).toHaveBeenCalledOnce();});
 it("write-first resolves phone then persists real provider IDs",async()=>{const s=await setup();await s.router.routeAmoOutbound({message:{conversation:{id:"amo-new"},source:{external_id:"source-1"},receiver:{id:"amo-wrong",phone:"+79991234567"},message:{id:"amo-write-first",type:"text",text:"hello"}}},"scope-1");expect(s.a.resolve).toHaveBeenCalledWith({phone:"79991234567",username:undefined});expect((s.a.send.mock.calls[0]![0] as SendMessageCommand).recipientId).toBe("provider-user-42");expect((await s.store.findConversationByAmoId("amo-new"))?.writeFirstState).toBe("pending");});
 it("keeps multiple accounts isolated by source and mapping",async()=>{const s=await setup();await s.accounts.upsert({id:"account-2",messenger:"telegram",providerAccountId:"p2",credentialRef:"s2",amoAccountId:"amo-1",amoScopeId:"scope-1",sourceExternalId:"source-2",config:{},state:"connected"});const a2=adapter("telegram","account-2","user-2");s.registry.register(a2.value);await s.router.routeAmoOutbound({message:{conversation:{id:"amo-2"},source:{external_id:"source-2"},receiver:{phone:"+7002"},message:{id:"m2",type:"text",text:"two"}}},"scope-1");expect(a2.send).toHaveBeenCalledOnce();expect(s.a.send).not.toHaveBeenCalled();});
 it("passes outbound media only through MediaStore before the provider",async()=>{const s=await setup();await s.store.upsertConversation({messenger:"telegram",messengerAccountId:"account-1",providerConversationId:"tg-chat",providerRecipientId:"tg-user",amoConversationId:"amo-media",amoScopeId:"scope-1"});const mediaStore={ingestRemote:vi.fn(async()=>({url:"https://signed-storage/media",size:12,mimeType:"image/jpeg"})),put:vi.fn()};const router=new MessageRouter({accounts:s.accounts,store:s.store,adapters:s.registry,chats:s.chats,mediaStore:mediaStore as any});await router.routeAmoOutbound({message:{conversation:{id:"amo-media"},message:{id:"media-1",type:"picture",media:"https://amojo.amocrm.ru/file",file_name:"photo.jpg"}}},"scope-1");expect(mediaStore.ingestRemote).toHaveBeenCalledOnce();expect((s.a.send.mock.calls[0]![0] as SendMessageCommand).attachments?.[0]?.url).toBe("https://signed-storage/media");});
 it("marks an ambiguous provider timeout delivery_unknown instead of allowing blind retry",async()=>{const s=await setup();await s.store.upsertConversation({messenger:"telegram",messengerAccountId:"account-1",providerConversationId:"tg-chat",providerRecipientId:"tg-user",amoConversationId:"amo-unknown",amoScopeId:"scope-1"});s.a.send.mockRejectedValueOnce(new DOMException("timeout","TimeoutError"));await expect(s.router.routeAmoOutbound({message:{conversation:{id:"amo-unknown"},message:{id:"ambiguous-1",type:"text",text:"hello"}}},"scope-1")).rejects.toThrow("may have accepted");expect((await s.store.findMessageByAmoId("ambiguous-1"))?.status).toBe("delivery_unknown");});
});
