import{describe,expect,it,vi}from"vitest";
import{MessageRouter}from"../src/router/message-router.js";
import{InMemoryMappingStore}from"../src/storage/mapping-store.js";
import{InMemoryAccountRepository}from"../src/storage/account-repository.js";
import{InMemoryAdapterRegistry,type MessengerAdapter}from"../src/adapters/messenger-adapter.js";
import type{NormalizedMessage,SendMessageCommand}from"../src/domain/messages.js";
import{InMemorySecretStore}from"../src/security/secret-store.js";
import{ContactChatResolver}from"../src/amocrm/contact-resolver.js";

function telegramAdapter():{value:MessengerAdapter;send:ReturnType<typeof vi.fn>;resolve:ReturnType<typeof vi.fn>}{const send=vi.fn(async()=>({externalMessageId:"provider-message",status:"sent" as const,occurredAt:new Date()}));const resolve=vi.fn(async()=>({providerRecipientId:"provider-user-42",providerConversationId:"conversation-provider-user-42",providerRecipientRef:{kind:"telegram_input_peer_user" as const,userId:"provider-user-42",accessHash:"stored-hash"}}));return{send,resolve,value:{kind:"telegram",accountId:"account-1",connect:async()=>{},disconnect:async()=>{},send,onInbound:()=>{},onStatus:()=>{},health:async()=>({connected:true}),resolveRecipient:resolve,resolveRecipientById:async()=>({providerRecipientRef:{kind:"telegram_input_peer_user",userId:"provider-user-42",accessHash:"stored-hash"}})}};}
async function setup(){const accounts=new InMemoryAccountRepository();await accounts.upsert({id:"account-1",messenger:"telegram",providerAccountId:"provider-account",credentialRef:"secret",amoAccountId:"amo-1",amoScopeId:"scope-1",sourceExternalId:"source-1",config:{},state:"connected"});const store=new InMemoryMappingStore(),secrets=new InMemorySecretStore(),registry=new InMemoryAdapterRegistry(),a=telegramAdapter();registry.register(a.value);const chats={sendMessage:vi.fn(async()=>({new_message:{msgid:"amo-message"}})),updateDeliveryStatus:vi.fn()} as any;return{accounts,store,secrets,registry,a,chats};}
const inbound:NormalizedMessage={id:"in-1",messenger:"telegram",accountId:"account-1",conversationId:"provider-chat",direction:"inbound",sender:{externalId:"provider-user",phone:"+79990000000"},text:"hello",attachments:[],occurredAt:new Date("2026-01-01T00:00:00Z"),status:"delivered"};

describe("full router flow",()=>{
 it("does not let a failing contact chat link block Telegram inbound",async()=>{const s=await setup();const rest={linkChatToContact:vi.fn(async()=>{throw new Error("HTTP 400");})};const resolver=new ContactChatResolver(rest as any,s.chats as any);const router=new MessageRouter({accounts:s.accounts,store:s.store,secrets:s.secrets,adapters:s.registry,chats:s.chats,contactResolver:resolver});const message={...inbound,sender:{externalId:"7093946401",displayName:"Telegram User",phone:"2349128858876",username:"ericafahelu",avatarUrl:"https://cdn.example/avatar.jpg",profile:{telegramId:"7093946401",firstName:"Telegram",lastName:"User",username:"ericafahelu",phone:"2349128858876",isBot:false}}};await expect(router.routeInbound(message)).resolves.toBeUndefined();expect(rest.linkChatToContact).not.toHaveBeenCalled();const payload=s.chats.sendMessage.mock.calls[0]![1].payload;expect(payload.sender).toMatchObject({name:"Telegram User",avatar:"https://cdn.example/avatar.jpg",profile:{phone:"2349128858876"},profile_link:"https://t.me/ericafahelu"});});
 it("preserves Telegram peer metadata only in SecretStore",async()=>{const s=await setup();const router=new MessageRouter({accounts:s.accounts,store:s.store,secrets:s.secrets,adapters:s.registry,chats:s.chats});await router.routeInbound({...inbound,sender:{externalId:"provider-user",displayName:"Ada Lovelace",username:"ada",profile:{telegramId:"provider-user",firstName:"Ada",lastName:"Lovelace",username:"ada",isBot:false},recipientReference:{kind:"telegram_input_peer_user",userId:"provider-user",accessHash:"safe-access-hash"}}});const mapping=await s.store.getConversation("telegram","account-1","provider-chat");expect(mapping).toMatchObject({providerRecipientSecretRef:"telegram-peer:account-1:provider-user",providerProfile:{telegramId:"provider-user",firstName:"Ada",lastName:"Lovelace",username:"ada",isBot:false}});expect(await s.secrets.get("telegram-peer:account-1:provider-user")).toEqual({kind:"telegram_input_peer_user",userId:"provider-user",accessHash:"safe-access-hash"});});
 it("write-first resolves phone then persists real provider IDs",async()=>{const s=await setup();const router=new MessageRouter({accounts:s.accounts,store:s.store,secrets:s.secrets,adapters:s.registry,chats:s.chats});await router.routeAmoOutbound({message:{conversation:{id:"amo-new"},receiver:{phone:"+79991234567"},message:{id:"amo-write-first",type:"text",text:"hello"}}},"scope-1");expect(s.a.resolve).toHaveBeenCalledWith({phone:"79991234567",username:undefined});expect((s.a.send.mock.calls[0]![0] as SendMessageCommand).recipientId).toBe("provider-user-42");});
 it("links a Write First reply through conversation_ref_id",async()=>{const s=await setup();const router=new MessageRouter({accounts:s.accounts,store:s.store,secrets:s.secrets,adapters:s.registry,chats:s.chats});await s.store.upsertConversation({messenger:"telegram",messengerAccountId:"account-1",providerConversationId:"tg-conversation",providerRecipientId:"tg-user",amoConversationId:"amo-write-first",amoScopeId:"scope-1",writeFirstState:"pending"});await router.routeInbound({...inbound,conversationId:"tg-conversation",sender:{externalId:"tg-user",phone:"+79991234567",profile:{telegramId:"tg-user",phone:"+79991234567"}}});expect(s.chats.sendMessage.mock.calls[0]![1].payload.conversation_ref_id).toBe("amo-write-first");});
});
