import { describe, expect, it, vi } from "vitest";
import { TelegramOnboardingService } from "../src/runtime/telegram-onboarding.js";
import { AdapterFactory } from "../src/runtime/adapter-runtime.js";
import { InMemoryAccountRepository } from "../src/storage/account-repository.js";
import { InMemorySecretStore } from "../src/security/secret-store.js";
import { InMemoryJobQueue } from "../src/queue/in-memory-job-queue.js";

describe("Telegram onboarding recovery",()=>{
 it("reauthorizes an existing account in place and replaces its credential secret",async()=>{const accounts=new InMemoryAccountRepository();const secrets=new InMemorySecretStore();await accounts.upsert({id:"9c05c6ec-17a4-4378-bccf-9af6ea902a6f",messenger:"telegram",providerAccountId:"+79990000000",credentialRef:"telegram:9c05c6ec-17a4-4378-bccf-9af6ea902a6f",amoAccountId:"amo",sourceExternalId:"source",config:{phone:"+79990000000"},state:"reconnect_required"});await secrets.put("telegram:9c05c6ec-17a4-4378-bccf-9af6ea902a6f",{apiId:1,apiHash:"old-hash",session:""});const disconnect=vi.fn(async()=>undefined);const service=new TelegramOnboardingService(secrets,accounts,()=>({authorize:async prompts=>{await prompts.phoneCode();return "authorized-session";},disconnect}));const started=await service.start({accountId:"9c05c6ec-17a4-4378-bccf-9af6ea902a6f",phone:"+79990000000",apiId:42,apiHash:"new-hash",amoAccountId:"ignored",sourceExternalId:"ignored"});expect(started.accountId).toBe("9c05c6ec-17a4-4378-bccf-9af6ea902a6f");expect(await secrets.get("telegram:9c05c6ec-17a4-4378-bccf-9af6ea902a6f")).toMatchObject({session:""});await expect(service.submitCode(started.accountId,"12345")).resolves.toEqual({status:"completed"});expect(await accounts.listAll()).toHaveLength(1);expect(await accounts.get(started.accountId)).toMatchObject({credentialRef:"telegram:9c05c6ec-17a4-4378-bccf-9af6ea902a6f",sourceExternalId:"source",state:"disconnected"});expect(await secrets.get("telegram:9c05c6ec-17a4-4378-bccf-9af6ea902a6f")).toEqual({apiId:42,apiHash:"new-hash",session:"authorized-session",authorized:true});expect(disconnect).toHaveBeenCalledOnce();});
 it("does not construct a Telegram client for a missing or unauthorised session",async()=>{const accounts=new InMemoryAccountRepository();const secrets=new InMemorySecretStore();const queue=new InMemoryJobQueue();await secrets.put("telegram:empty",{apiId:1,apiHash:"hash",session:"",authorized:false});await expect(new AdapterFactory(secrets,queue).create({id:"empty",messenger:"telegram",providerAccountId:"p",credentialRef:"telegram:empty",amoAccountId:"amo",sourceExternalId:"source",config:{},state:"reconnect_required"})).rejects.toThrow("authorization required");});
});
