import{createHmac}from"node:crypto";import{describe,expect,it,vi}from"vitest";import{buildWebhookServer}from"../src/webhooks/server.js";import{InMemoryJobQueue}from"../src/queue/in-memory-job-queue.js";import{InMemoryAccountRepository}from"../src/storage/account-repository.js";import{InMemorySecretStore}from"../src/security/secret-store.js";
describe("durable webhook ACK",()=>{
 it("atomically enqueues amoCRM payload and ACKs without business processing",async()=>{const queue=new InMemoryJobQueue();const app=buildWebhookServer({queue,amoChannelSecret:"channel-secret-1234567890"});const raw='{ "message": {"conversation":{"id":"c1"},"message":{"id":"m1"}}}';const signature=createHmac("sha1","channel-secret-1234567890").update(raw).digest("hex");const response=await app.inject({method:"POST",url:"/webhooks/amocrm/scope-1",headers:{"content-type":"application/json","x-signature":signature},payload:raw});expect(response.statusCode).toBe(200);expect((await queue.counts()).pending).toBe(1);await app.close();},15000);
 it("deduplicates repeated amoCRM webhook",async()=>{const queue=new InMemoryJobQueue();const app=buildWebhookServer({queue,amoChannelSecret:"channel-secret-1234567890"});const raw='{"message":{"conversation":{"id":"c1"},"message":{"id":"m1"}}}';const signature=createHmac("sha1","channel-secret-1234567890").update(raw).digest("hex");for(let i=0;i<2;i++)await app.inject({method:"POST",url:"/webhooks/amocrm/scope",headers:{"content-type":"application/json","x-signature":signature},payload:raw});expect((await queue.counts()).pending).toBe(1);await app.close();});
 it("rejects bad signature before database enqueue",async()=>{const queue=new InMemoryJobQueue();const app=buildWebhookServer({queue,amoChannelSecret:"channel-secret-1234567890"});const r=await app.inject({method:"POST",url:"/webhooks/amocrm/scope",headers:{"content-type":"application/json","x-signature":"bad"},payload:{message:{}}});expect(r.statusCode).toBe(401);expect((await queue.counts()).pending).toBe(0);await app.close();});
 it("returns 503 when amoCRM channel secret is not configured",async()=>{const queue=new InMemoryJobQueue();const app=buildWebhookServer({queue});const r=await app.inject({method:"POST",url:"/webhooks/amocrm/scope",headers:{"content-type":"application/json"},payload:{message:{conversation:{id:"c1"},message:{id:"m1"}}}});expect(r.statusCode).toBe(503);await app.close();});
 it("stores External Integration OAuth credentials without returning them",async()=>{const queue=new InMemoryJobQueue();const secrets=new InMemorySecretStore();const exchangeAuthorizationCode=vi.fn(async()=>undefined);const app=buildWebhookServer({queue,oauth:{secrets,redirectUri:"https://sinaichannel.ru/oauth/callback",exchangeAuthorizationCode}});const received=await app.inject({method:"POST",url:"/oauth/secrets",payload:{client_id:"client-uuid",client_secret:"client-secret",state:"opaque"}});expect(received.statusCode).toBe(204);expect(received.body).toBe("");expect(await secrets.get("amocrm:external-client")).toEqual({clientId:"client-uuid",clientSecret:"client-secret",state:"opaque"});const callback=await app.inject({method:"GET",url:"/oauth/callback?code=authorization-code"});expect(callback.statusCode).toBe(200);expect(exchangeAuthorizationCode).toHaveBeenCalledWith("authorization-code");expect(callback.body).not.toContain("authorization-code");await app.close();});
 it("lists admin accounts and supports disconnect",async()=>{const queue=new InMemoryJobQueue();const accounts=new InMemoryAccountRepository();await accounts.upsert({id:"a1",messenger:"telegram",providerAccountId:"+1",credentialRef:"telegram:a1",amoAccountId:"amo1",sourceExternalId:"src1",config:{phone:"+1"},state:"connected"});const supervisor={disconnectAccount:vi.fn(async()=>undefined),reconnectAccount:vi.fn(async()=>undefined)} as any;const {AccountAdminService}=await import("../src/runtime/account-admin.js");const adminSvc=new AccountAdminService(accounts,supervisor);const app=buildWebhookServer({queue,amoChannelSecret:"channel-secret-1234567890",adminToken:"admin-token-that-is-at-least-32-chars",accountAdmin:adminSvc});const auth={authorization:"Bearer admin-token-that-is-at-least-32-chars"};const list=await app.inject({method:"GET",url:"/admin/accounts",headers:auth});expect(list.statusCode).toBe(200);expect(JSON.parse(list.body)).toHaveLength(1);const disc=await app.inject({method:"POST",url:"/admin/accounts/a1/disconnect",headers:auth});expect(disc.statusCode).toBe(200);expect(supervisor.disconnectAccount).toHaveBeenCalledWith("a1");await app.close();});
 it("delegates confirmed-not-accepted recovery to one atomic store operation",async()=>{const queue=new InMemoryJobQueue();const directRequeue=vi.spyOn(queue,"requeueDead");const confirmNotAccepted=vi.fn(async()=>true);const mappings={listDeliveryUnknown:vi.fn(),reconcileDeliveryUnknown:vi.fn()} as any;const app=buildWebhookServer({queue,amoChannelSecret:"channel-secret-1234567890",adminToken:"admin-token-that-is-at-least-32-chars",mappings,deliveryReconciliation:{confirmNotAccepted}});const r=await app.inject({method:"POST",url:"/admin/deliveries/amo-1/reconcile",headers:{authorization:"Bearer admin-token-that-is-at-least-32-chars"},payload:{accepted:false,jobId:42}});expect(r.statusCode).toBe(200);expect(confirmNotAccepted).toHaveBeenCalledWith("amo-1",42);expect(directRequeue).not.toHaveBeenCalled();await app.close();});
});
