import{describe,expect,it,vi}from"vitest";import{InMemoryJobQueue}from"../src/queue/in-memory-job-queue.js";import{DurableWorker,retryDecision}from"../src/queue/worker.js";import{HttpError}from"../src/http/http-error.js";import{DeliveryUnknownError}from"../src/core/errors.js";
describe("durable worker",()=>{
 it("recovers a crashed worker lease after restart",async()=>{let now=new Date("2026-01-01T00:00:00Z");const q=new InMemoryJobQueue(()=>now);await q.enqueue({kind:"messenger.inbound",partitionKey:"chat",dedupeKey:"1",payload:{}});await q.claim("crashed");now=new Date(now.getTime()+2000);expect(await q.recoverStale(1000)).toBe(1);const handler=vi.fn(async()=>{});const w=new DurableWorker({queue:q,handlers:{"messenger.inbound":handler},workerId:"restart"});await w.pollOnce();expect(handler).toHaveBeenCalledOnce();expect((await q.counts()).completed).toBe(1);});
 it("preserves partition ordering",async()=>{const q=new InMemoryJobQueue();await q.enqueue({kind:"messenger.inbound",partitionKey:"same-chat",dedupeKey:"1",payload:{n:1}});await q.enqueue({kind:"messenger.inbound",partitionKey:"same-chat",dedupeKey:"2",payload:{n:2}});const first=await q.claim("w1");expect(await q.claim("w2")).toBeUndefined();await q.complete(first!.id,"w1");expect((await q.claim("w2"))?.dedupeKey).toBe("2");});
 it("honours Retry-After and does not retry permanent 4xx",()=>{expect(retryDecision(new HttpError(429,"POST","https://api",2500),1,{random:()=>0})).toEqual({retry:true,delayMs:2500});expect(retryDecision(new HttpError(400,"POST","https://api"),1,{}).retry).toBe(false);});
 it("moves permanent failures to dead letter",async()=>{const q=new InMemoryJobQueue();await q.enqueue({kind:"messenger.inbound",partitionKey:"x",dedupeKey:"x",payload:{}});const w=new DurableWorker({queue:q,handlers:{"messenger.inbound":async()=>{throw new HttpError(400,"POST","https://api");}},workerId:"w"});await w.pollOnce();expect((await q.counts()).dead).toBe(1);});
 it("does not retry arbitrary validation errors",()=>{expect(retryDecision(new Error("invalid mapping"),1,{})).toEqual({retry:false,delayMs:0});});
 it("rejects a duplicate key carrying a different payload",async()=>{const q=new InMemoryJobQueue();await q.enqueue({kind:"messenger.inbound",partitionKey:"x",dedupeKey:"same",payload:{value:1}});await expect(q.enqueue({kind:"messenger.inbound",partitionKey:"x",dedupeKey:"same",payload:{value:2}})).rejects.toThrow("different payload");});
 it("survives a temporary queue infrastructure failure",async()=>{const q=new InMemoryJobQueue();await q.enqueue({kind:"messenger.inbound",partitionKey:"x",dedupeKey:"recover",payload:{}});const original=q.claim.bind(q);vi.spyOn(q,"claim").mockRejectedValueOnce(Object.assign(new Error("database unavailable"),{code:"ECONNRESET"})).mockImplementation(original);const controller=new AbortController();const handler=vi.fn(async()=>controller.abort());const worker=new DurableWorker({queue:q,handlers:{"messenger.inbound":handler},infrastructureRetryMs:1});await worker.start(controller.signal);expect(handler).toHaveBeenCalledOnce();expect((await q.counts()).completed).toBe(1);});
 it("requires explicit reconciliation before an unknown delivery can be requeued",async()=>{const q=new InMemoryJobQueue();const inserted=await q.enqueue({kind:"amocrm.outbound",partitionKey:"x",dedupeKey:"unknown",payload:{}});const worker=new DurableWorker({queue:q,handlers:{"amocrm.outbound":async()=>{throw new DeliveryUnknownError();}}});await worker.pollOnce();expect(await q.requeueDead(inserted.id)).toBe(false);expect(await q.requeueDead(inserted.id,true)).toBe(true);});
});
