import type { AmoCrmChatsClient } from "../amocrm/chats-client.js";
import type { ContactChatResolver } from "../amocrm/contact-resolver.js";
import type { AdapterRegistry } from "../adapters/messenger-adapter.js";
import type { AccountRepository } from "../domain/accounts.js";
import type { MessengerKind,NormalizedAttachment,NormalizedMessage,SendMessageCommand,MessageStatus } from "../domain/messages.js";
import type { MappingStore,ConversationMapping } from "../storage/mapping-store.js";
import type{MediaStore}from"../media/media-store.js";
import{DeliveryUnknownError}from"../core/errors.js";
import{HttpError}from"../http/http-error.js";
import type { SecretStore } from "../security/secret-store.js";
import { getTelegramPeer,storeTelegramPeer } from "../runtime/telegram-peer-secrets.js";
import { TelegramRecipientResolutionError } from "../core/errors.js";

interface Options {store:MappingStore;accounts:AccountRepository;adapters:AdapterRegistry;chats:AmoCrmChatsClient;secrets:SecretStore;contactResolver?:ContactChatResolver;mediaStore?:MediaStore;now?:()=>Date;}

export class MessageRouter {
 private readonly now:()=>Date;
 constructor(private readonly options:Options){this.now=options.now??(()=>new Date());}

 async routeInbound(input:NormalizedMessage):Promise<void>{
  const message={...input,occurredAt:new Date(input.occurredAt)};const account=await this.options.accounts.get(message.accountId);if(!account||account.messenger!==message.messenger)throw new Error(`Unknown ${message.messenger} account ${message.accountId}`);if(!account.amoScopeId)throw new Error(`Account ${account.id} has no amoCRM scope_id`);
  let mapping=await this.options.store.getConversation(message.messenger,account.id,message.conversationId);
  const recipientSecretRef=await this.persistInboundPeer(message);
  if(!mapping){mapping={messenger:message.messenger,messengerAccountId:account.id,providerConversationId:message.conversationId,providerRecipientId:message.sender.externalId,...(recipientSecretRef?{providerRecipientSecretRef:recipientSecretRef}:{}),...(message.sender.profile?{providerProfile:message.sender.profile}:{}),amoScopeId:account.amoScopeId,writeFirstState:"none",lastInboundAt:message.occurredAt};
   if(message.sender.phone&&this.options.contactResolver){const contact=await this.options.contactResolver.findExactByPhone(message.sender.phone);if(contact){const chat=await this.options.contactResolver.createChatAndLink(account,message.conversationId,message.sender,contact);mapping.amoConversationId=chat.amoConversationId;mapping.amoContactId=contact.contactId;mapping.amoLeadId=contact.leadId;}}
  } else {mapping.lastInboundAt=message.occurredAt;if(recipientSecretRef)mapping.providerRecipientSecretRef=recipientSecretRef;mapping.providerRecipientRef=undefined;if(message.sender.profile)mapping.providerProfile=message.sender.profile;if(mapping.amoContactId&&this.options.contactResolver)await this.options.contactResolver.enrich(mapping.amoContactId,message.sender);if(mapping.writeFirstState==="pending")mapping.writeFirstState="linked";}
  const parts=message.attachments.length?message.attachments:[undefined];
  for(let i=0;i<parts.length;i++){const externalId=parts.length===1?message.id:`${message.id}:${i}`;const response:any=await this.options.chats.sendMessage(account.amoScopeId,amoPayload(message,externalId,parts[i],mapping));await this.options.store.saveMessage({messenger:message.messenger,messengerAccountId:account.id,messengerMessageId:externalId,providerConversationId:message.conversationId,amoMessageId:response?.new_message?.msgid,amoConversationId:mapping.amoConversationId,direction:"inbound",status:"sent",occurredAt:message.occurredAt,statusAt:this.now()});}
  await this.options.store.upsertConversation(mapping);
 }

 async routeAmoOutbound(hook:any,scopeId:string):Promise<void>{
  const data=hook?.message??hook;const amoMessageId=String(data?.message?.id??"");const amoConversationId=String(data?.conversation?.id??"");if(!amoMessageId||!amoConversationId)throw new Error("Invalid amoCRM Chats v2 message webhook");const previous=await this.options.store.findMessageByAmoId(amoMessageId);if(previous){if(previous.status==="delivery_unknown")throw new DeliveryUnknownError("Outbound send requires provider reconciliation");return;}
  let mapping=await this.options.store.findConversationByAmoId(amoConversationId);
  if(!mapping&&data?.conversation?.client_id){const base=await this.resolveAccount(scopeId,data);mapping=await this.options.store.getConversation(base.messenger,base.id,String(data.conversation.client_id));if(mapping){mapping.amoConversationId=amoConversationId;await this.options.store.upsertConversation(mapping);}}
  if(!mapping){try{const account=await this.resolveAccount(scopeId,data);const adapter=this.requiredAdapter(account.messenger,account.id);const phone=normalizePhone(data?.receiver?.phone);const username=typeof data?.receiver?.username==="string"?data.receiver.username:undefined;if(phone){mapping=await this.options.store.findConversationByPhone(account.messenger,account.id,phone);if(mapping){mapping.amoConversationId=amoConversationId;mapping.writeFirstState="pending";await this.options.store.upsertConversation(mapping);}}if(!mapping){if(!phone&&!username)throw new Error("Telegram recipient phone is required");const recipient=await adapter.resolveRecipient({phone,username});const providerRecipientSecretRef=recipient.providerRecipientRef?await storeTelegramPeer(this.options.secrets,account.id,recipient.providerRecipientRef):undefined;mapping={messenger:account.messenger,messengerAccountId:account.id,providerConversationId:recipient.providerConversationId,providerRecipientId:recipient.providerRecipientId,...(providerRecipientSecretRef?{providerRecipientSecretRef}:{}),...(recipient.providerProfile?{providerProfile:recipient.providerProfile}:{}),amoConversationId,amoScopeId:account.amoScopeId!,writeFirstState:"pending"};await this.options.store.upsertConversation(mapping);}}catch{await this.options.chats.updateDeliveryStatus(scopeId,amoMessageId,{status_code:-1,error_code:904,error:"Telegram recipient could not be resolved for this phone number"});return;}}
  const account=await this.options.accounts.get(mapping.messengerAccountId);if(!account)throw new Error(`Mapped account ${mapping.messengerAccountId} not found`);const adapter=this.requiredAdapter(mapping.messenger,mapping.messengerAccountId);
  let attachments=amoWebhookAttachments(data?.message);if(attachments.length){if(!this.options.mediaStore)throw new Error("Outbound media requires MediaStore");attachments=await Promise.all(attachments.map(async a=>({...a,...await this.options.mediaStore!.ingestRemote({url:a.url!,kind:a.kind,fileName:a.fileName,sourceId:`amo:${amoMessageId}`} )})));}
  const recipientReference=await this.recipientReference(mapping);const command:SendMessageCommand={accountId:account.id,conversationId:required(mapping.providerConversationId,"provider conversation"),recipientId:mapping.providerRecipientId,recipientReference,text:data?.message?.text,attachments,idempotencyKey:amoMessageId};
  await this.options.store.saveMessage({messenger:mapping.messenger,messengerAccountId:account.id,messengerMessageId:`delivery-unknown:${amoMessageId}`,providerConversationId:command.conversationId,amoMessageId,amoConversationId,direction:"outbound",status:"delivery_unknown",statusAt:this.now(),occurredAt:this.now()});let result;try{result=await adapter.send(command);}catch(error){if(isAmbiguousSend(error))throw error instanceof DeliveryUnknownError?error:new DeliveryUnknownError("Provider may have accepted the outbound message",{cause:error});await this.options.store.clearDeliveryUnknown(amoMessageId);throw error;}const finalStatus=result.status==="queued"||result.status==="sent"||result.status==="delivered"||result.status==="read"?result.status:"sent";let recorded=false;try{recorded=await this.options.store.reconcileDeliveryUnknown(amoMessageId,result.externalMessageId,finalStatus);}catch(error){throw new DeliveryUnknownError("Provider accepted the message but result persistence is ambiguous",{cause:error});}if(!recorded)throw new DeliveryUnknownError("Provider accepted the message but its result was not durably recorded");
  if(result.status!=="sent"&&result.status!=="queued")await this.pushStatus(mapping.amoScopeId,amoMessageId,result.status);
 }

 async routeStatus(payload:{messenger:MessengerKind;accountId:string;id:string;status:MessageStatus;occurredAt:string|Date}):Promise<void>{const at=new Date(payload.occurredAt);const message=await this.options.store.findMessageByMessengerId(payload.messenger,payload.accountId,payload.id);await this.options.store.updateMessageStatus(payload.messenger,payload.accountId,payload.id,payload.status,at);if(!message?.amoMessageId||!message.amoConversationId||payload.status==="sent"||payload.status==="queued")return;const mapping=await this.options.store.findConversationByAmoId(message.amoConversationId);if(mapping)await this.pushStatus(mapping.amoScopeId,message.amoMessageId,payload.status);}
 private async pushStatus(scope:string,id:string,status:MessageStatus){await this.options.chats.updateDeliveryStatus(scope,id,status==="read"?{status_code:2}:status==="delivered"?{status_code:1}:{status_code:-1,error_code:905,error:"Messenger reported delivery failure"});}
 private requiredAdapter(k:MessengerKind,id:string){const a=this.options.adapters.get(k,id);if(!a)throw new Error(`Adapter ${k}:${id} is not connected`);return a;}
 private async persistInboundPeer(message:NormalizedMessage):Promise<string|undefined>{if(message.messenger!=="telegram")return undefined;if(message.sender.recipientSecretRef)return message.sender.recipientSecretRef;if(!message.sender.recipientReference)return undefined;return storeTelegramPeer(this.options.secrets,message.accountId,message.sender.recipientReference);}
 private async recipientReference(mapping:ConversationMapping){if(mapping.messenger!=="telegram")return undefined;let secretRef=mapping.providerRecipientSecretRef;if(!secretRef&&mapping.providerRecipientRef){secretRef=await storeTelegramPeer(this.options.secrets,mapping.messengerAccountId,mapping.providerRecipientRef);mapping.providerRecipientSecretRef=secretRef;mapping.providerRecipientRef=undefined;await this.options.store.upsertConversation(mapping);}if(!secretRef){const adapter=this.requiredAdapter(mapping.messenger,mapping.messengerAccountId);if(!adapter.resolveRecipientById)throw new TelegramRecipientResolutionError();const recovered=await adapter.resolveRecipientById(mapping.providerRecipientId);secretRef=await storeTelegramPeer(this.options.secrets,mapping.messengerAccountId,recovered.providerRecipientRef);mapping.providerRecipientSecretRef=secretRef;mapping.providerProfile=recovered.providerProfile??mapping.providerProfile;await this.options.store.upsertConversation(mapping);}const reference=await getTelegramPeer(this.options.secrets,secretRef);if(!reference)throw new TelegramRecipientResolutionError();return reference;}
 private async resolveAccount(scope:string,_data:any){const account=await this.options.accounts.findByScope(scope);if(!account)throw new Error(`No messenger account mapped to scope ${scope}`);if(!account.amoScopeId)throw new Error(`Account ${account.id} has no scope`);return account;}
}

function amoPayload(m:NormalizedMessage,msgid:string,a:NormalizedAttachment|undefined,map:ConversationMapping){if(a&&!a.url)throw new Error(`Attachment ${a.id??msgid} has no amoCRM-reachable URL`);const type=a?({image:"picture",video:"video",audio:"audio",voice:"voice",sticker:"sticker",file:"file",unknown:"file"}as const)[a.kind]:"text";return{event_type:"new_message",payload:{timestamp:Math.floor(m.occurredAt.getTime()/1000),msec_timestamp:m.occurredAt.getTime(),msgid,conversation_id:m.conversationId,...(map.amoConversationId?{conversation_ref_id:map.amoConversationId}:{}),sender:{id:m.sender.externalId,name:m.sender.displayName??m.sender.username??m.sender.externalId,...(m.sender.avatarUrl?{avatar:m.sender.avatarUrl}:{}),...(m.sender.phone?{profile:{phone:m.sender.phone}}:{}),...(m.sender.username?{profile_link:`https://t.me/${m.sender.username.replace(/^@/,"")}`}:{})},message:{type,text:a?.caption??m.text??"",...(a?.url?{media:a.url}:{...((type!=="text")?{}:{})}),...(a&&type!=="audio"&&type!=="voice"&&type!=="sticker"?{file_name:a.fileName??`${msgid}.${extension(a.mimeType)}`,file_size:a.size}:{} )},silent:false}};}
function amoWebhookAttachments(m:any):NormalizedAttachment[]{if(!m?.media)return[];const kind=({picture:"image",video:"video",audio:"audio",voice:"voice",sticker:"sticker",file:"file"}as any)[m.type]??"unknown";return[{kind,url:m.media,fileName:m.file_name,size:m.file_size}];}
function normalizePhone(v:unknown){if(typeof v!=="string")return undefined;const d=v.replace(/\D/g,"");return d||undefined;}
function required<T>(v:T|undefined,name:string):T{if(v===undefined)throw new Error(`Missing ${name}`);return v;}
function extension(mime?:string){return mime?.split("/")[1]?.replace(/[^a-z0-9]/gi,"")||"bin";}
function isAmbiguousSend(error:unknown){if(error instanceof DeliveryUnknownError)return true;if(error instanceof HttpError)return error.status===408||error.status>=500;const e=error as any;return error instanceof TypeError||e?.name==="TimeoutError"||e?.name==="AbortError"||["ECONNRESET","ETIMEDOUT","UND_ERR_CONNECT_TIMEOUT","UND_ERR_SOCKET"].includes(String(e?.code??""));}
