import type { Pool } from "pg";
import type { AccountRepository,AccountState,MessengerAccount } from "../domain/accounts.js";
import type { MessengerKind } from "../domain/messages.js";

export class PostgresAccountRepository implements AccountRepository {
 constructor(private readonly pool:Pool){}
 async get(id:string){const r=await this.pool.query("SELECT * FROM messenger_accounts WHERE id=$1",[id]);return r.rows[0]?row(r.rows[0]):undefined;}
 async findByProvider(m:MessengerKind,p:string){const r=await this.pool.query("SELECT * FROM messenger_accounts WHERE messenger=$1 AND provider_account_id=$2 AND state<>'disabled' ORDER BY id LIMIT 1",[m,p]);return r.rows[0]?row(r.rows[0]):undefined;}
 async findByScope(s:string){const r=await this.pool.query("SELECT * FROM messenger_accounts WHERE amo_scope_id=$1",[s]);return r.rows[0]?row(r.rows[0]):undefined;}
 async findByScopeAndSource(s:string,source:string){const r=await this.pool.query("SELECT * FROM messenger_accounts WHERE amo_scope_id=$1 AND source_external_id=$2 AND state<>'disabled' ORDER BY id LIMIT 1",[s,source]);return r.rows[0]?row(r.rows[0]):undefined;}
 async listEnabled(){const r=await this.pool.query("SELECT * FROM messenger_accounts WHERE state IN ('connected','error') ORDER BY id");return r.rows.map(row);}
 async listAll(){const r=await this.pool.query("SELECT * FROM messenger_accounts ORDER BY created_at,id");return r.rows.map(row);}
 async upsert(x:MessengerAccount){await this.pool.query(`INSERT INTO messenger_accounts(id,messenger,provider_account_id,display_name,credential_ref,amo_account_id,amo_scope_id,source_external_id,config,state,last_error) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11) ON CONFLICT(id) DO UPDATE SET provider_account_id=EXCLUDED.provider_account_id,display_name=EXCLUDED.display_name,credential_ref=EXCLUDED.credential_ref,amo_account_id=EXCLUDED.amo_account_id,amo_scope_id=EXCLUDED.amo_scope_id,source_external_id=EXCLUDED.source_external_id,config=EXCLUDED.config,state=EXCLUDED.state,last_error=EXCLUDED.last_error,updated_at=now()`,[x.id,x.messenger,x.providerAccountId,x.displayName,x.credentialRef,x.amoAccountId,x.amoScopeId,x.sourceExternalId,JSON.stringify(x.config),x.state,x.lastError]);}
 async delete(id:string){const client=await this.pool.connect();try{await client.query("BEGIN");const found=await client.query<{credential_ref:string}>("SELECT credential_ref FROM messenger_accounts WHERE id=$1 FOR UPDATE",[id]);if(!found.rows[0]){await client.query("ROLLBACK");return false;}const credentialRef=found.rows[0].credential_ref;await client.query("DELETE FROM message_mappings WHERE messenger_account_id=$1",[id]);await client.query("DELETE FROM conversation_mappings WHERE messenger_account_id=$1",[id]);await client.query("DELETE FROM messenger_accounts WHERE id=$1",[id]);await client.query("DELETE FROM secrets WHERE id=$1 OR (id LIKE 'telegram-peer:%' AND substring(id from char_length('telegram-peer:') + 1 for char_length($2))=$2 AND substring(id from char_length('telegram-peer:') + char_length($2) + 1 for 1)=':')",[credentialRef,id]);await client.query("COMMIT");return true;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
 async setScope(id:string,s:string){await this.pool.query("UPDATE messenger_accounts SET amo_scope_id=$2,updated_at=now() WHERE id=$1",[id,s]);}
 async setState(id:string,s:AccountState,e?:string){await this.pool.query("UPDATE messenger_accounts SET state=$2,last_error=$3,last_connected_at=CASE WHEN $2='connected' THEN now() ELSE last_connected_at END,updated_at=now() WHERE id=$1",[id,s,e?.slice(0,1000)]);}
}
export class InMemoryAccountRepository implements AccountRepository {private xs:MessengerAccount[]=[];async get(id:string){return this.xs.find(x=>x.id===id);}async findByProvider(m:MessengerKind,p:string){return this.xs.find(x=>x.messenger===m&&x.providerAccountId===p&&x.state!=="disabled");}async findByScope(s:string){return this.xs.find(x=>x.amoScopeId===s);}async findByScopeAndSource(s:string,source:string){return this.xs.find(x=>x.amoScopeId===s&&x.sourceExternalId===source&&x.state!=="disabled");}async listEnabled(){return this.xs.filter(x=>x.state==="connected"||x.state==="error");}async listAll(){return [...this.xs].sort((a,b)=>a.id.localeCompare(b.id));}async upsert(x:MessengerAccount){const old=await this.get(x.id);if(old)Object.assign(old,x);else this.xs.push({...x});}async delete(id:string){const i=this.xs.findIndex(x=>x.id===id);if(i<0)return false;this.xs.splice(i,1);return true;}async setScope(id:string,s:string){const x=await this.get(id);if(x)x.amoScopeId=s;}async setState(id:string,s:AccountState,e?:string){const x=await this.get(id);if(x){x.state=s;x.lastError=e;}}}
function row(r:any):MessengerAccount{return{id:r.id,messenger:r.messenger,providerAccountId:r.provider_account_id,displayName:r.display_name,credentialRef:r.credential_ref,amoAccountId:r.amo_account_id,amoScopeId:r.amo_scope_id,sourceExternalId:r.source_external_id,config:r.config??{},state:r.state,lastError:r.last_error};}
