import type { Pool } from "pg";
import type { MappingStore,ConversationMapping,MessageMapping } from "./mapping-store.js";
import type { MessengerKind,MessageStatus } from "../domain/messages.js";

export class PostgresMappingStore implements MappingStore {
 constructor(private readonly pool:Pool){}
 async getConversation(m:MessengerKind,a:string,c:string){const r=await this.pool.query("SELECT * FROM conversation_mappings WHERE messenger=$1 AND messenger_account_id=$2 AND provider_conversation_id=$3",[m,a,c]);return r.rows[0]?conv(r.rows[0]):undefined;}
 async findConversationByRecipient(m:MessengerKind,a:string,p:string){const r=await this.pool.query("SELECT * FROM conversation_mappings WHERE messenger=$1 AND messenger_account_id=$2 AND provider_recipient_id=$3",[m,a,p]);return r.rows[0]?conv(r.rows[0]):undefined;}
 async findConversationByPhone(m:MessengerKind,a:string,p:string){const r=await this.pool.query("SELECT * FROM conversation_mappings WHERE messenger=$1 AND messenger_account_id=$2 AND regexp_replace(COALESCE(provider_profile->>'phone',''),'\\D','','g')=$3 ORDER BY updated_at DESC LIMIT 1",[m,a,p]);return r.rows[0]?conv(r.rows[0]):undefined;}
 async findConversationByAmoId(id:string){const r=await this.pool.query("SELECT * FROM conversation_mappings WHERE amo_conversation_id=$1",[id]);return r.rows[0]?conv(r.rows[0]):undefined;}
 async upsertConversation(x:ConversationMapping){await this.pool.query(`INSERT INTO conversation_mappings(messenger,messenger_account_id,provider_conversation_id,provider_recipient_id,provider_recipient_ref,provider_recipient_secret_ref,provider_profile,amo_conversation_id,amo_contact_id,amo_lead_id,amo_scope_id,write_first_state,last_inbound_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(messenger,messenger_account_id,provider_recipient_id) DO UPDATE SET provider_conversation_id=COALESCE(EXCLUDED.provider_conversation_id,conversation_mappings.provider_conversation_id),provider_recipient_ref=EXCLUDED.provider_recipient_ref,provider_recipient_secret_ref=COALESCE(EXCLUDED.provider_recipient_secret_ref,conversation_mappings.provider_recipient_secret_ref),provider_profile=COALESCE(EXCLUDED.provider_profile,conversation_mappings.provider_profile),amo_conversation_id=COALESCE(EXCLUDED.amo_conversation_id,conversation_mappings.amo_conversation_id),amo_contact_id=COALESCE(EXCLUDED.amo_contact_id,conversation_mappings.amo_contact_id),amo_lead_id=COALESCE(EXCLUDED.amo_lead_id,conversation_mappings.amo_lead_id),amo_scope_id=EXCLUDED.amo_scope_id,write_first_state=EXCLUDED.write_first_state,last_inbound_at=COALESCE(EXCLUDED.last_inbound_at,conversation_mappings.last_inbound_at),updated_at=now()`,[x.messenger,x.messengerAccountId,x.providerConversationId,x.providerRecipientId,x.providerRecipientRef??null,x.providerRecipientSecretRef??null,x.providerProfile??null,x.amoConversationId,x.amoContactId,x.amoLeadId,x.amoScopeId,x.writeFirstState??"none",x.lastInboundAt]);}
 async saveMessage(x:MessageMapping){await this.pool.query(`INSERT INTO message_mappings(messenger,messenger_account_id,messenger_message_id,provider_conversation_id,amo_message_id,amo_conversation_id,direction,status,status_at,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(messenger,messenger_account_id,messenger_message_id) DO UPDATE SET amo_message_id=COALESCE(EXCLUDED.amo_message_id,message_mappings.amo_message_id),amo_conversation_id=COALESCE(EXCLUDED.amo_conversation_id,message_mappings.amo_conversation_id),status=EXCLUDED.status,status_at=EXCLUDED.status_at,updated_at=now()`,[x.messenger,x.messengerAccountId,x.messengerMessageId,x.providerConversationId,x.amoMessageId,x.amoConversationId,x.direction,x.status,x.statusAt??x.occurredAt,x.occurredAt]);}
 async findMessageByAmoId(id:string){const r=await this.pool.query("SELECT * FROM message_mappings WHERE amo_message_id=$1",[id]);return r.rows[0]?msg(r.rows[0]):undefined;}
 async findMessageByMessengerId(m:MessengerKind,a:string,id:string){const r=await this.pool.query("SELECT * FROM message_mappings WHERE messenger=$1 AND messenger_account_id=$2 AND messenger_message_id=$3",[m,a,id]);return r.rows[0]?msg(r.rows[0]):undefined;}
  async updateMessageStatus(m:MessengerKind,a:string,id:string,s:MessageStatus,at=new Date()){await this.pool.query(`UPDATE message_mappings SET status=$4,status_at=$5,updated_at=now() WHERE messenger=$1 AND messenger_account_id=$2 AND messenger_message_id=$3 AND $5>=status_at AND ($4='failed' OR CASE $4 WHEN 'queued' THEN 0 WHEN 'sent' THEN 1 WHEN 'delivered' THEN 2 WHEN 'read' THEN 3 END >= CASE status WHEN 'queued' THEN 0 WHEN 'sent' THEN 1 WHEN 'delivered' THEN 2 WHEN 'read' THEN 3 ELSE -1 END)`,[m,a,id,s,at]);}
 async listDeliveryUnknown(limit:number){const r=await this.pool.query("SELECT * FROM message_mappings WHERE status='delivery_unknown' ORDER BY occurred_at LIMIT $1",[Math.min(500,Math.max(1,limit))]);return r.rows.map(msg);}
 async reconcileDeliveryUnknown(amoId:string,providerId:string,status:"queued"|"sent"|"delivered"|"read"){const r=await this.pool.query("UPDATE message_mappings SET messenger_message_id=$2,status=$3,status_at=now(),updated_at=now() WHERE amo_message_id=$1 AND status='delivery_unknown'",[amoId,providerId,status]);return r.rowCount===1;}
 async clearDeliveryUnknown(amoId:string){const r=await this.pool.query("DELETE FROM message_mappings WHERE amo_message_id=$1 AND status='delivery_unknown'",[amoId]);return r.rowCount===1;}
}
function conv(r:any):ConversationMapping{return{messenger:r.messenger,messengerAccountId:r.messenger_account_id,providerConversationId:r.provider_conversation_id,providerRecipientId:r.provider_recipient_id,providerRecipientRef:r.provider_recipient_ref??undefined,providerRecipientSecretRef:r.provider_recipient_secret_ref??undefined,providerProfile:r.provider_profile??undefined,amoConversationId:r.amo_conversation_id,amoContactId:r.amo_contact_id?Number(r.amo_contact_id):undefined,amoLeadId:r.amo_lead_id?Number(r.amo_lead_id):undefined,amoScopeId:r.amo_scope_id,writeFirstState:r.write_first_state,lastInboundAt:r.last_inbound_at?new Date(r.last_inbound_at):undefined};}
function msg(r:any):MessageMapping{return{messenger:r.messenger,messengerAccountId:r.messenger_account_id,messengerMessageId:r.messenger_message_id,providerConversationId:r.provider_conversation_id,amoMessageId:r.amo_message_id,amoConversationId:r.amo_conversation_id,direction:r.direction,status:r.status,statusAt:new Date(r.status_at),occurredAt:new Date(r.occurred_at)};}
