import { Pool } from "pg";
import type { MappingStore, ConversationMapping, MessageMapping } from "./mapping-store.js";
import type { MessengerKind, MessageStatus } from "../domain/messages.js";

export class PostgresMappingStore implements MappingStore {
  constructor(private readonly pool: Pool) {}
  async reserveEvent(provider: string, id: string, hash: string): Promise<boolean> { const r = await this.pool.query("INSERT INTO webhook_events(provider, external_event_id, payload_hash, state) VALUES($1,$2,$3,'processing') ON CONFLICT(provider,external_event_id) DO UPDATE SET state='processing',attempts=webhook_events.attempts+1,last_error=NULL WHERE webhook_events.state='failed' RETURNING id", [provider,id,hash]); return r.rowCount === 1; }
  async completeEvent(provider: string, id: string): Promise<void> { await this.pool.query("UPDATE webhook_events SET state='complete', processed_at=now() WHERE provider=$1 AND external_event_id=$2", [provider,id]); }
  async failEvent(provider: string, id: string, error: string): Promise<void> { await this.pool.query("UPDATE webhook_events SET state='failed', last_error=$3, attempts=attempts+1 WHERE provider=$1 AND external_event_id=$2", [provider,id,error.slice(0,1000)]); }
  async getConversation(m: MessengerKind, a: string, c: string): Promise<ConversationMapping|undefined> { const r=await this.pool.query("SELECT * FROM conversation_mappings WHERE messenger=$1 AND messenger_account_id=$2 AND messenger_conversation_id=$3",[m,a,c]); return r.rows[0] ? rowConversation(r.rows[0]) : undefined; }
  async findConversationByAmoId(id: string): Promise<ConversationMapping|undefined> { const r=await this.pool.query("SELECT * FROM conversation_mappings WHERE amo_conversation_id=$1",[id]); return r.rows[0] ? rowConversation(r.rows[0]) : undefined; }
  async upsertConversation(x: ConversationMapping): Promise<void> { await this.pool.query(`INSERT INTO conversation_mappings(messenger,messenger_account_id,messenger_conversation_id,amo_conversation_id,amo_contact_id,amo_lead_id,amo_scope_id) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(messenger,messenger_account_id,messenger_conversation_id) DO UPDATE SET amo_conversation_id=COALESCE(EXCLUDED.amo_conversation_id,conversation_mappings.amo_conversation_id),amo_contact_id=COALESCE(EXCLUDED.amo_contact_id,conversation_mappings.amo_contact_id),amo_lead_id=COALESCE(EXCLUDED.amo_lead_id,conversation_mappings.amo_lead_id),amo_scope_id=EXCLUDED.amo_scope_id,updated_at=now()`,[x.messenger,x.messengerAccountId,x.messengerConversationId,x.amoConversationId,x.amoContactId,x.amoLeadId,x.amoScopeId]); }
  async saveMessage(x: MessageMapping): Promise<void> { await this.pool.query(`INSERT INTO message_mappings(messenger,messenger_account_id,messenger_message_id,messenger_conversation_id,amo_message_id,amo_conversation_id,direction,status,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(messenger,messenger_account_id,messenger_message_id) DO UPDATE SET amo_message_id=COALESCE(EXCLUDED.amo_message_id,message_mappings.amo_message_id),amo_conversation_id=COALESCE(EXCLUDED.amo_conversation_id,message_mappings.amo_conversation_id),status=EXCLUDED.status,updated_at=now()`,[x.messenger,x.messengerAccountId,x.messengerMessageId,x.messengerConversationId,x.amoMessageId,x.amoConversationId,x.direction,x.status,x.occurredAt]); }
  async findMessageByAmoId(id:string):Promise<MessageMapping|undefined>{const r=await this.pool.query("SELECT * FROM message_mappings WHERE amo_message_id=$1",[id]);return r.rows[0]?rowMessage(r.rows[0]):undefined;}
  async findMessageByMessengerId(m:MessengerKind,a:string,id:string):Promise<MessageMapping|undefined>{const r=await this.pool.query("SELECT * FROM message_mappings WHERE messenger=$1 AND messenger_account_id=$2 AND messenger_message_id=$3",[m,a,id]);return r.rows[0]?rowMessage(r.rows[0]):undefined;}
  async updateMessageStatus(m:MessengerKind,a:string,id:string,s:MessageStatus):Promise<void>{await this.pool.query("UPDATE message_mappings SET status=$4,updated_at=now() WHERE messenger=$1 AND messenger_account_id=$2 AND messenger_message_id=$3 AND ($4='failed' OR CASE $4 WHEN 'queued' THEN 0 WHEN 'sent' THEN 1 WHEN 'delivered' THEN 2 WHEN 'read' THEN 3 END >= CASE status WHEN 'queued' THEN 0 WHEN 'sent' THEN 1 WHEN 'delivered' THEN 2 WHEN 'read' THEN 3 ELSE -1 END)",[m,a,id,s]);}
}

function rowConversation(r:any):ConversationMapping{return{messenger:r.messenger,messengerAccountId:r.messenger_account_id,messengerConversationId:r.messenger_conversation_id,amoConversationId:r.amo_conversation_id,amoContactId:r.amo_contact_id?Number(r.amo_contact_id):undefined,amoLeadId:r.amo_lead_id?Number(r.amo_lead_id):undefined,amoScopeId:r.amo_scope_id};}
function rowMessage(r:any):MessageMapping{return{messenger:r.messenger,messengerAccountId:r.messenger_account_id,messengerMessageId:r.messenger_message_id,messengerConversationId:r.messenger_conversation_id,amoMessageId:r.amo_message_id,amoConversationId:r.amo_conversation_id,direction:r.direction,status:r.status,occurredAt:new Date(r.occurred_at)};}
