import{z}from"zod";
const bool=z.string().optional().transform(v=>v===undefined?true:!["false","0","no"].includes(v.toLowerCase()));
const falseBool=z.string().optional().transform(v=>v!==undefined&&["true","1","yes"].includes(v.toLowerCase()));
const optionalText=(schema:z.ZodTypeAny)=>z.preprocess(v=>v===""?undefined:v,schema.optional());
const schema=z.object({
 AMOCRM_ENVIRONMENT:z.enum(["production","test"]).default("production"),
 AMOCRM_BASE_URL:z.string().url(),AMOCRM_ACCESS_TOKEN:optionalText(z.string().min(1)),AMOCRM_READ_ONLY:bool,AMOCRM_WRITES_ENABLED:falseBool,AMOCRM_EXPECTED_ACCOUNT_ID:optionalText(z.string().min(1)),AMOCRM_EXPECTED_SUBDOMAIN:optionalText(z.string().regex(/^[a-z0-9-]+$/i)),
 AMOCRM_REFRESH_TOKEN:optionalText(z.string().min(1)),AMOCRM_INTEGRATION_ID:optionalText(z.string().min(1)),AMOCRM_CLIENT_SECRET:optionalText(z.string().min(1)),AMOCRM_REDIRECT_URI:optionalText(z.string().url()),AMOCRM_TOKEN_EXPIRES_AT:optionalText(z.coerce.number().positive()),
 AMOCRM_OAUTH_PROFILE:z.enum(["legacy","private"]).default("legacy"),AMOCRM_PRIVATE_INTEGRATION_ID:optionalText(z.string().min(1)),AMOCRM_PRIVATE_CLIENT_SECRET:optionalText(z.string().min(1)),AMOCRM_PRIVATE_REDIRECT_URI:optionalText(z.string().url()),AMOCRM_SOURCES_WRITES_ENABLED:falseBool,AMOCRM_CHATS_ORIGIN_CODE:optionalText(z.string().min(1).max(100)),
 AMOCRM_CHATS_BASE_URL:z.string().url().default("https://amojo.amocrm.ru"),AMOCRM_CHATS_CHANNEL_ID:optionalText(z.string().min(1)),AMOCRM_CHATS_CHANNEL_SECRET:optionalText(z.string().min(20)),
 AMOCRM_CONTACT_TELEGRAM_NAME_FIELD_ID:optionalText(z.coerce.number().int().positive()),AMOCRM_CONTACT_TELEGRAM_USERNAME_FIELD_ID:optionalText(z.coerce.number().int().positive()),AMOCRM_CONTACT_TELEGRAM_ID_FIELD_ID:optionalText(z.coerce.number().int().positive()),
 AMOCRM_DEFAULT_ACCOUNT_ID:optionalText(z.string().min(1)),AMOCRM_DEFAULT_SOURCE_EXTERNAL_ID:z.string().min(1).max(36),TELEGRAM_API_ID:z.coerce.number().int().positive(),TELEGRAM_API_HASH:z.string().min(1),PUBLIC_DOMAIN:optionalText(z.string().min(1)),
 DATABASE_URL:z.string().min(1),SECRET_MASTER_KEY:z.string().min(32),ADMIN_API_TOKEN:z.string().min(32),
 S3_ENDPOINT:optionalText(z.string().url()),S3_REGION:z.string().min(1),S3_BUCKET:z.string().min(1),S3_ACCESS_KEY_ID:z.string().min(1),S3_SECRET_ACCESS_KEY:z.string().min(1),S3_FORCE_PATH_STYLE:z.string().optional().transform(v=>v==="true"),MEDIA_URL_TTL_SECONDS:z.coerce.number().int().min(900).max(604800).default(86400),MEDIA_MAX_BYTES:z.coerce.number().int().positive().default(25*1024*1024),MEDIA_ALLOWED_HOSTS:z.string().min(1).default("amojo.amocrm.ru,amojo.amocrm.com"),MEDIA_DOWNLOAD_TIMEOUT_MS:z.coerce.number().int().positive().default(15000),CLAMAV_HOST:z.string().min(1),CLAMAV_PORT:z.coerce.number().int().positive().default(3310),
 PORT:z.coerce.number().int().positive().default(3000),LOG_LEVEL:z.string().default("info"),WEBHOOK_BODY_LIMIT_BYTES:z.coerce.number().int().positive().default(2*1024*1024),WEBHOOK_RATE_LIMIT_PER_MINUTE:z.coerce.number().int().positive().default(300),WORKER_CONCURRENCY:z.coerce.number().int().min(1).max(64).default(4),WORKER_LEASE_MS:z.coerce.number().int().positive().default(60000),WORKER_POLL_MS:z.coerce.number().int().positive().default(250),WORKER_INFRA_RETRY_MS:z.coerce.number().int().positive().default(1000),COMPLETED_JOB_PAYLOAD_RETENTION_HOURS:z.coerce.number().int().positive().default(24),JOB_RETENTION_DAYS:z.coerce.number().int().positive().default(30),DEAD_JOB_RETENTION_DAYS:z.coerce.number().int().positive().default(90),JOB_CLEANUP_INTERVAL_MS:z.coerce.number().int().positive().default(3600000),SHUTDOWN_TIMEOUT_MS:z.coerce.number().int().positive().default(30000),
}).superRefine((value,ctx)=>{if(value.AMOCRM_WRITES_ENABLED&&(value.AMOCRM_READ_ONLY||!value.AMOCRM_EXPECTED_ACCOUNT_ID||!value.AMOCRM_EXPECTED_SUBDOMAIN||!value.AMOCRM_ACCESS_TOKEN))ctx.addIssue({code:z.ZodIssueCode.custom,path:["AMOCRM_WRITES_ENABLED"],message:"amoCRM writes require READ_ONLY=false, an access token, expected account ID and subdomain"});if(!value.AMOCRM_READ_ONLY&&!value.AMOCRM_WRITES_ENABLED)ctx.addIssue({code:z.ZodIssueCode.custom,path:["AMOCRM_READ_ONLY"],message:"READ_ONLY=false requires explicit AMOCRM_WRITES_ENABLED=true"});const legacyClient=[value.AMOCRM_INTEGRATION_ID,value.AMOCRM_CLIENT_SECRET,value.AMOCRM_REDIRECT_URI];const privateClient=[value.AMOCRM_PRIVATE_INTEGRATION_ID,value.AMOCRM_PRIVATE_CLIENT_SECRET,value.AMOCRM_PRIVATE_REDIRECT_URI];if(legacyClient.some(Boolean)&&!legacyClient.every(Boolean))ctx.addIssue({code:z.ZodIssueCode.custom,path:["AMOCRM_INTEGRATION_ID"],message:"legacy amoCRM OAuth client ID, secret and redirect URI must be configured together"});if(privateClient.some(Boolean)&&!privateClient.every(Boolean))ctx.addIssue({code:z.ZodIssueCode.custom,path:["AMOCRM_PRIVATE_INTEGRATION_ID"],message:"private amoCRM OAuth client ID, secret and redirect URI must be configured together"});const selected=value.AMOCRM_OAUTH_PROFILE==="private"?privateClient:legacyClient;if(value.AMOCRM_OAUTH_PROFILE==="private"&&!privateClient.every(Boolean))ctx.addIssue({code:z.ZodIssueCode.custom,path:["AMOCRM_OAUTH_PROFILE"],message:"private OAuth profile requires private client settings"});if(value.AMOCRM_SOURCES_WRITES_ENABLED&&(!value.AMOCRM_EXPECTED_ACCOUNT_ID||!value.AMOCRM_EXPECTED_SUBDOMAIN||!value.AMOCRM_CHATS_ORIGIN_CODE))ctx.addIssue({code:z.ZodIssueCode.custom,path:["AMOCRM_SOURCES_WRITES_ENABLED"],message:"source writes require expected amoCRM target and Chats origin code"});if(value.AMOCRM_REFRESH_TOKEN&&(!legacyClient.every(Boolean)||!value.AMOCRM_ACCESS_TOKEN))ctx.addIssue({code:z.ZodIssueCode.custom,path:["AMOCRM_REFRESH_TOKEN"],message:"amoCRM OAuth refresh token requires legacy OAuth client settings and an access token"});if(!value.AMOCRM_ACCESS_TOKEN&&!selected.every(Boolean))ctx.addIssue({code:z.ZodIssueCode.custom,path:["AMOCRM_ACCESS_TOKEN"],message:"an access token or complete selected amoCRM OAuth client settings are required"});});
export type AppConfig=z.infer<typeof schema>;export function loadConfig(env:NodeJS.ProcessEnv=process.env):AppConfig{return schema.parse(env);}
