import"dotenv/config";
import{Pool}from"pg";
import{HeadBucketCommand,S3Client}from"@aws-sdk/client-s3";
import{loadConfig}from"./config.js";import{createLogger}from"./logging.js";
import{AmoCrmRestClient}from"./amocrm/rest-client.js";import{AmoCrmChatsClient}from"./amocrm/chats-client.js";import{AmoChatsLifecycle}from"./amocrm/lifecycle.js";
import{exchangeAmoAuthorizationCode,RefreshingAmoTokenProvider}from"./amocrm/oauth-token-provider.js";
import{verifyAmoWriteTarget}from"./amocrm/write-target-gate.js";
import{PostgresMappingStore}from"./storage/postgres-store.js";import{PostgresAccountRepository}from"./storage/account-repository.js";import{validateSchema}from"./storage/migrations.js";
import{PostgresDeliveryReconciliationStore}from"./storage/delivery-reconciliation.js";
import{EncryptedPostgresSecretStore}from"./security/secret-store.js";import{PostgresJobQueue}from"./queue/postgres-job-queue.js";import{DurableWorker}from"./queue/worker.js";import{createRuntimeHandlers}from"./queue/runtime-handlers.js";
import{InMemoryAdapterRegistry}from"./adapters/messenger-adapter.js";import{AdapterFactory,ReconnectSupervisor}from"./runtime/adapter-runtime.js";import{TelegramOnboardingService}from"./runtime/telegram-onboarding.js";import{AccountManagementService}from"./runtime/account-management.js";import{AccountAdminService}from"./runtime/account-admin.js";
import{SafeMediaDownloader}from"./media/safe-downloader.js";import{S3MediaStore}from"./media/s3-media-store.js";import{ClamAvScanner}from"./media/clamav-scanner.js";import{MessageRouter}from"./router/message-router.js";import{buildWebhookServer}from"./webhooks/server.js";
import{retentionLoop}from"./queue/retention-service.js";

const c=loadConfig();const logger=createLogger(c.LOG_LEVEL);
const pool=new Pool({connectionString:c.DATABASE_URL,max:Math.max(10,c.WORKER_CONCURRENCY+5),statement_timeout:30_000,query_timeout:30_000});await validateSchema(pool);
const secrets=new EncryptedPostgresSecretStore(pool,c.SECRET_MASTER_KEY);const accounts=new PostgresAccountRepository(pool);const mappings=new PostgresMappingStore(pool);const deliveryReconciliation=new PostgresDeliveryReconciliationStore(pool);const queue=new PostgresJobQueue(pool);const registry=new InMemoryAdapterRegistry();
const s3=new S3Client({region:c.S3_REGION,endpoint:c.S3_ENDPOINT,forcePathStyle:c.S3_FORCE_PATH_STYLE,credentials:{accessKeyId:c.S3_ACCESS_KEY_ID,secretAccessKey:c.S3_SECRET_ACCESS_KEY}});
const scanner=new ClamAvScanner(c.CLAMAV_HOST,c.CLAMAV_PORT);const downloader=new SafeMediaDownloader({maxBytes:c.MEDIA_MAX_BYTES,timeoutMs:c.MEDIA_DOWNLOAD_TIMEOUT_MS,allowedHosts:c.MEDIA_ALLOWED_HOSTS.split(",").map(x=>x.trim()).filter(Boolean)});const media=new S3MediaStore({client:s3,bucket:c.S3_BUCKET,urlTtlSeconds:c.MEDIA_URL_TTL_SECONDS,maxBytes:c.MEDIA_MAX_BYTES,downloader,scanner,timeoutMs:c.MEDIA_DOWNLOAD_TIMEOUT_MS});
if(c.AMOCRM_WRITES_ENABLED){const verifier=new AmoCrmRestClient({baseUrl:c.AMOCRM_BASE_URL,accessToken:c.AMOCRM_ACCESS_TOKEN!,readOnly:true});await verifyAmoWriteTarget(verifier,{accountId:c.AMOCRM_EXPECTED_ACCOUNT_ID!,subdomain:c.AMOCRM_EXPECTED_SUBDOMAIN!});}const credentialRef="amocrm:primary";const oauthConfigured=Boolean(c.AMOCRM_INTEGRATION_ID&&c.AMOCRM_CLIENT_SECRET&&c.AMOCRM_REDIRECT_URI);let tokenProvider:{getAccessToken():Promise<string>}|undefined;if(oauthConfigured){if(c.AMOCRM_REFRESH_TOKEN&&!await secrets.get(credentialRef))await secrets.put(credentialRef,{accessToken:c.AMOCRM_ACCESS_TOKEN!,refreshToken:c.AMOCRM_REFRESH_TOKEN,expiresAt:c.AMOCRM_TOKEN_EXPIRES_AT??Date.now()+20*60*60*1000});tokenProvider=new RefreshingAmoTokenProvider({baseUrl:c.AMOCRM_BASE_URL,integrationId:c.AMOCRM_INTEGRATION_ID!,clientSecret:c.AMOCRM_CLIENT_SECRET!,redirectUri:c.AMOCRM_REDIRECT_URI!,credentialRef,secrets,writesAllowed:c.AMOCRM_WRITES_ENABLED});}const rest=new AmoCrmRestClient({baseUrl:c.AMOCRM_BASE_URL,...(tokenProvider?{tokenProvider}:{accessToken:c.AMOCRM_ACCESS_TOKEN!}),readOnly:!c.AMOCRM_WRITES_ENABLED,logger});const chatsConfigured=Boolean(c.AMOCRM_CHATS_CHANNEL_ID&&c.AMOCRM_CHATS_CHANNEL_SECRET);const chats=new AmoCrmChatsClient({baseUrl:c.AMOCRM_CHATS_BASE_URL,channelId:c.AMOCRM_CHATS_CHANNEL_ID??"",channelSecret:c.AMOCRM_CHATS_CHANNEL_SECRET??"",readOnly:!c.AMOCRM_WRITES_ENABLED});const lifecycle=new AmoChatsLifecycle(rest,chats,accounts,logger);
const telegramSettings={apiId:c.TELEGRAM_API_ID,apiHash:c.TELEGRAM_API_HASH,sourceExternalId:c.AMOCRM_DEFAULT_SOURCE_EXTERNAL_ID};const factory=new AdapterFactory(secrets,queue,media,c.MEDIA_MAX_BYTES,telegramSettings);const supervisor=new ReconnectSupervisor(accounts,registry,factory,logger);await supervisor.reconcile();const router=new MessageRouter({store:mappings,accounts,adapters:registry,chats,secrets,mediaStore:media});const handlers=createRuntimeHandlers(router,registry);const onboarding=new TelegramOnboardingService(secrets,accounts,telegramSettings,undefined,logger);const accountManagement=new AccountManagementService(accounts,secrets);const accountAdmin=new AccountAdminService(accounts,supervisor,onboarding);const webhookBase=c.PUBLIC_DOMAIN?`https://${c.PUBLIC_DOMAIN.replace(/^https?:\/\//,"")}`:undefined;

const app=buildWebhookServer({
 queue,amoChannelSecret:c.AMOCRM_CHATS_CHANNEL_SECRET,
 readiness:async()=>{try{await pool.query("SELECT 1");await s3.send(new HeadBucketCommand({Bucket:c.S3_BUCKET}),{abortSignal:AbortSignal.timeout(c.MEDIA_DOWNLOAD_TIMEOUT_MS)});const clam=await scanner.health();const jobs=await queue.counts();return{ready:clam,detail:{database:true,objectStorage:true,clamav:clam,jobs,chatsChannelConfigured:chatsConfigured}};}catch(error){return{ready:false,detail:{error:error instanceof Error?error.message:"dependency failure"}};}},
 onboarding,accountManagement,accountAdmin,lifecycle,mappings,deliveryReconciliation,adminToken:c.ADMIN_API_TOKEN,
 bootstrap:{publicDomain:c.PUBLIC_DOMAIN,amoAccountIdDefault:c.AMOCRM_DEFAULT_ACCOUNT_ID,sourceExternalIdDefault:c.AMOCRM_DEFAULT_SOURCE_EXTERNAL_ID,chatsChannelConfigured:chatsConfigured,webhookUrlTemplate:webhookBase?`${webhookBase}/webhooks/amocrm/{scope_id}`:undefined},
 oauth:{redirectUri:c.AMOCRM_REDIRECT_URI,secrets,exchangeAuthorizationCode:oauthConfigured?code=>exchangeAmoAuthorizationCode({baseUrl:c.AMOCRM_BASE_URL,integrationId:c.AMOCRM_INTEGRATION_ID!,clientSecret:c.AMOCRM_CLIENT_SECRET!,redirectUri:c.AMOCRM_REDIRECT_URI!,credentialRef,secrets,writesAllowed:c.AMOCRM_WRITES_ENABLED},code):undefined},
 logger,bodyLimit:c.WEBHOOK_BODY_LIMIT_BYTES,rateLimitMax:c.WEBHOOK_RATE_LIMIT_PER_MINUTE,
});
const controller=new AbortController();const workers=Array.from({length:c.WORKER_CONCURRENCY},(_,i)=>new DurableWorker({queue,handlers,workerId:`${process.pid}-${i}`,leaseMs:c.WORKER_LEASE_MS,pollMs:c.WORKER_POLL_MS,infrastructureRetryMs:c.WORKER_INFRA_RETRY_MS,logger}).start(controller.signal));const retain=retentionLoop(queue,{payloadHours:c.COMPLETED_JOB_PAYLOAD_RETENTION_HOURS,completedDays:c.JOB_RETENTION_DAYS,deadDays:c.DEAD_JOB_RETENTION_DAYS,intervalMs:c.JOB_CLEANUP_INTERVAL_MS},controller.signal,logger);const supervise=supervisor.run(controller.signal).catch(error=>logger.error({error:error instanceof Error?error.message:"supervisor failed"},"supervisor stopped"));await app.listen({port:c.PORT,host:"0.0.0.0"});
let stopping=false;async function shutdown(signal:string){if(stopping)return;stopping=true;logger.info({signal},"graceful shutdown");controller.abort();await app.close();await supervisor.shutdown();await Promise.race([Promise.allSettled([...workers,supervise,retain]),new Promise(r=>setTimeout(r,c.SHUTDOWN_TIMEOUT_MS))]);await pool.end();}
process.once("SIGTERM",()=>void shutdown("SIGTERM"));process.once("SIGINT",()=>void shutdown("SIGINT"));
